In [97]:
import pandas as pd

In [98]:
TR = 3  # teams to be relegated

In [99]:
pd.set_option('display.max_columns', None)

In [100]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [101]:
df = pd.read_csv('data/20260220/ekstraklasa_relegation_odds_raw.csv')

In [102]:
df.head()

,Team Name,Odds - Betclic,Odds - STS,Odds - efortuna,Prob - fmd [%],Prob - opta/own [%]
0,Termalica Bruk-Bet Nieciecza,1.25,1.25,1.30,69.8,69.8
1,Arka Gdynia,1.40,1.40,1.40,57.3,53.7
2,Motor Lublin,2.25,2.25,2.25,34.9,38.9
3,Piast Gliwice,3.75,3.75,3.75,8.4,10.0
4,GKS Katowice,5.00,5.00,5.50,7.5,7.1

In [103]:
for bookie in ['Betclic', 'STS', 'efortuna']:
    spread = sum(1 / df[f'Odds - {bookie}'])
    if bookie == 'Betclic':
        df[f'Breakeven Prob - {bookie} - tax adj. [%]'] = df.apply(lambda x: round(100 / (x[f'Odds - {bookie}']), 1), axis=1)
    else:
        df[f'Breakeven Prob - {bookie} - tax adj. [%]'] = df.apply(lambda x: round(100 / ((x[f'Odds - {bookie}']) * 0.88), 1), axis=1)
    df[f'Implied Prob - {bookie} - raw [%]'] = df.apply(lambda x: round(100 / x[f'Odds - {bookie}'], 1), axis=1)
    df[f'Implied Prob - {bookie} - spread adj. [%]'] = df.apply(lambda x: round(100 / x[f'Odds - {bookie}'] * (TR / spread), 1), axis=1)

In [104]:
df.head(18)

,Team Name,Odds - Betclic,Odds - STS,Odds - efortuna,Prob - fmd [%],Prob - opta/own [%],Breakeven Prob - Betclic - tax adj. [%],Implied Prob - Betclic - raw [%],Implied Prob - Betclic - spread adj. [%],Breakeven Prob - STS - tax adj. [%],Implied Prob - STS - raw [%],Implied Prob - STS - spread adj. [%],Breakeven Prob - efortuna - tax adj. [%],Implied Prob - efortuna - raw [%],Implied Prob - efortuna - spread adj. [%]
0,Termalica Bruk-Bet Nieciecza,1.25,1.25,1.30,69.8,69.8,80.0,80.0,74.7,90.9,80.0,74.7,87.4,76.9,69.4
1,Arka Gdynia,1.40,1.40,1.40,57.3,53.7,71.4,71.4,66.7,81.2,71.4,66.7,81.2,71.4,64.5
2,Motor Lublin,2.25,2.25,2.25,34.9,38.9,44.4,44.4,41.5,50.5,44.4,41.5,50.5,44.4,40.1
3,Piast Gliwice,3.75,3.75,3.75,8.4,10.0,26.7,26.7,24.9,30.3,26.7,24.9,30.3,26.7,24.1
4,GKS Katowice,5.00,5.00,5.50,7.5,7.1,20.0,20.0,18.7,22.7,20.0,18.7,20.7,18.2,16.4
5,Legia Warszawa,5.00,5.00,4.50,40.6,46.4,20.0,20.0,18.7,22.7,20.0,18.7,25.3,22.2,20.1
6,Pogoń Szczecin,7.50,7.50,6.00,16.2,21.2,13.3,13.3,12.5,15.2,13.3,12.5,18.9,16.7,15.0
7,Lechia Gdańsk,9.00,9.00,7.50,9.1,6.1,11.1,11.1,10.4,12.6,11.1,10.4,15.2,13.3,12.0
8,RKS Radomiak,9.00,9.00,9.00,4.4,5.3,11.1,11.1,10.4,12.6,11.1,10.4,12.6,11.1,10.0
9,Widzew Łódź,9.00,9.00,6.00,46.0,37.6,11.1,11.1,10.4,12.6,11.1,10.4,18.9,16.7,15.0
10,Korona Kielce,15.00,15.00,12.00,2.5,1.6,6.7,6.7,6.2,7.6,6.7,6.2,9.5,8.3,7.5
11,Zagłębie Lubin,25.00,25.00,20.00,1.2,0.8,4.0,4.0,3.7,4.5,4.0,3.7,5.7,5.0,4.5
12,Wisła Płock,200.00,200.00,200.00,0.9,0.5,0.5,0.5,0.5,0.6,0.5,0.5,0.6,0.5,0.5
13,Cracovia,250.00,250.00,250.00,0.6,0.3,0.4,0.4,0.4,0.5,0.4,0.4,0.5,0.4,0.4
14,Górnik Zabrze,400.00,400.00,350.00,0.1,0.1,0.2,0.2,0.2,0.3,0.2,0.2,0.3,0.3,0.3
15,Raków Częstochowa,1000.00,1000.00,1000.00,0.1,0.3,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1
16,Lech Poznań,1500.00,2500.00,2000.00,0.3,0.2,0.1,0.1,0.1,0.0,0.0,0.0,0.1,0.1,0.0
17,Jagiellonia Białystok,1500.00,7500.00,5000.00,0.0,0.0,0.1,0.1,0.1,0.0,0.0,0.0,0.0,0.0,0.0