In [1]:
import statistics

import pandas as pd

from helpers import *
from regression import *

In [2]:
pd.set_option('display.max_columns', None)

In [3]:
%load_ext autoreload
%autoreload 2

In [4]:
CONFIG = {
    'elo_date': '2025-12-12',  # date for elo ratings from clubelo.com
    'opta_date': '2025-11-28',  # date for elo ratings from the opta -> clubelo regression; elo_date from day X is before the games are played, for opta it depends
    'number_of_sims': 10000,
    'league_id': 3,
    'season': 2025,
    'head_size': 36,
    'country_code_elo': 'UEL',  # use this attr. to use elo ratings from clubelo.com
    'country_code_api': None,  # use this attr. to use elo ratings from the opta -> clubelo regression
    'stdev': 0,
    'update_fixtures': True,
    'is_european_league': True,
    'round_no': 7,
}
code = CONFIG['country_code_elo'] if CONFIG['country_code_elo'] is not None else CONFIG['country_code_api']
CONFIG['sorting_order'] = get_sorting_order_for_country_code(code)

In [5]:
# download_elo_data(CONFIG['elo_date'])

In [6]:
# main_regression(**CONFIG)

In [7]:
standings_df = build_historical_standings_table_after_at_most_n_rounds(**CONFIG)
standings_df.head(CONFIG['head_size'])

,Club,Elo,Matches played,Wins,Draws,Losses,Goals for,Goals against,Goal difference,Points,Random order
1,Lyon,1737,6,5,0,1,13,3,10,15,26
2,FC Midtjylland,1679,6,5,0,1,13,5,8,15,1
3,Aston Villa,1912,6,5,0,1,10,4,6,15,15
4,Real Betis,1756,6,4,2,0,11,4,7,14,4
5,SC Freiburg,1711,6,4,2,0,9,3,6,14,9
6,Ferencvarosi TC,1543,6,4,2,0,11,6,5,14,24
7,SC Braga,1686,6,4,1,1,10,5,5,13,27
8,FC Porto,1768,6,4,1,1,9,5,4,13,14
9,VfB Stuttgart,1731,6,4,0,2,12,5,7,12,16
10,AS Roma,1808,6,4,0,2,10,5,5,12,30
11,Nottingham Forest,1776,6,3,2,1,11,6,5,11,7
12,Fenerbahçe,1698,6,3,2,1,9,5,4,11,13
13,Bologna,1766,6,3,2,1,9,5,4,11,5
14,Plzen,1566,6,2,4,0,6,2,4,10,12
15,Panathinaikos,1543,6,3,1,2,9,7,2,10,11
16,Genk,1591,6,3,1,2,7,6,1,10,31
17,FK Crvena Zvezda,1570,6,3,1,2,5,5,0,10,22
18,PAOK,1616,6,2,3,1,13,10,3,9,28
19,Celta Vigo,1683,6,3,0,3,12,9,3,9,19
20,Lille,1754,6,3,0,3,10,7,3,9,0
21,BSC Young Boys,1506,6,3,0,3,8,12,-4,9,35
22,Brann,1523,6,2,2,2,6,7,-1,8,17
23,Ludogorets,1448,6,2,1,3,11,14,-3,7,20
24,Celtic,1586,6,2,1,3,7,11,-4,7,2
25,Dinamo Zagreb,1520,6,2,1,3,8,13,-5,7,6
26,FC Basel 1893,1511,6,2,0,4,8,9,-1,6,10
27,FCSB,1448,6,2,0,4,7,11,-4,6,32
28,GO Ahead Eagles,1458,6,2,0,4,5,11,-6,6,23
29,Sturm Graz,1462,6,1,1,4,4,8,-4,4,18
30,Feyenoord,1638,6,1,0,5,7,13,-6,3,34
31,Red Bull Salzburg,1495,6,1,0,5,5,11,-6,3,8
32,Utrecht,1529,6,0,1,5,3,9,-6,1,25
33,Rangers,1508,6,0,1,5,3,11,-8,1,29
34,Malmo FF,1448,6,0,1,5,3,12,-9,1,21
35,Maccabi Tel Aviv,1450,6,0,1,5,2,18,-16,1,3
36,Nice,1606,6,0,0,6,4,13,-9,0,33

In [8]:
CONFIG['update_fixtures'] = False

In [9]:
float(round(standings_df['Points'].sum() / standings_df['Matches played'].sum(), 2))

1.42

In [10]:
sample_season = simulate_season_after_n_rounds(**CONFIG, standings_df=standings_df)
sample_season.head(CONFIG['head_size'])

,Club,Elo,Matches played,Wins,Draws,Losses,Goals for,Goals against,Goal difference,Points,Random order
1,Aston Villa,1912,8,7,0,1,14,4,10,21,16
2,SC Freiburg,1711,8,6,2,0,13,3,10,20,1
3,SC Braga,1686,8,6,1,1,14,5,9,19,19
4,Real Betis,1756,8,5,3,0,14,5,9,18,24
5,Lyon,1737,8,5,2,1,15,5,10,17,6
6,FC Porto,1768,8,5,2,1,12,6,6,17,7
7,AS Roma,1808,8,5,1,2,13,6,7,16,8
8,FC Midtjylland,1679,8,5,1,2,14,8,6,16,26
9,Celta Vigo,1683,8,5,0,3,16,9,7,15,31
10,Ferencvarosi TC,1543,8,4,3,1,12,9,3,15,23
11,Plzen,1566,8,3,5,0,9,3,6,14,34
12,Panathinaikos,1543,8,4,2,2,12,8,4,14,21
13,Fenerbahçe,1698,8,4,2,2,11,7,4,14,32
14,Bologna,1766,8,4,2,2,11,7,4,14,17
15,VfB Stuttgart,1731,8,4,1,3,13,8,5,13,33
16,FK Crvena Zvezda,1570,8,4,1,3,7,7,0,13,27
17,Nottingham Forest,1776,8,3,3,2,12,9,3,12,18
18,PAOK,1616,8,2,5,1,15,12,3,11,20
19,Genk,1591,8,3,2,3,8,9,-1,11,30
20,Brann,1523,8,3,2,3,8,9,-1,11,12
21,Dinamo Zagreb,1520,8,3,2,3,11,14,-3,11,0
22,BSC Young Boys,1506,8,3,2,3,10,14,-4,11,3
23,Celtic,1586,8,3,1,4,9,13,-4,10,29
24,Lille,1754,8,3,0,5,10,11,-1,9,35
25,Ludogorets,1448,8,2,3,3,13,16,-3,9,10
26,Sturm Graz,1462,8,2,2,4,7,9,-2,8,28
27,GO Ahead Eagles,1458,8,2,1,5,6,14,-8,7,2
28,FC Basel 1893,1511,8,2,0,6,8,13,-5,6,11
29,Red Bull Salzburg,1495,8,2,0,6,7,13,-6,6,9
30,FCSB,1448,8,2,0,6,7,15,-8,6,5
31,Feyenoord,1638,8,1,1,6,8,16,-8,4,13
32,Malmo FF,1448,8,1,1,6,5,14,-9,4,14
33,Maccabi Tel Aviv,1450,8,1,1,6,4,20,-16,4,22
34,Utrecht,1529,8,0,2,6,4,12,-8,2,25
35,Nice,1606,8,0,2,6,6,15,-9,2,4
36,Rangers,1508,8,0,2,6,4,14,-10,2,15

In [11]:
float(round(sample_season['Points'].sum() / sample_season['Matches played'].sum(), 2))

1.4

In [12]:
simulate_odds(**CONFIG, standings_df=standings_df).head(CONFIG['head_size'])

            Home Team          Away Team  Odds H  Odds D  Odds A
0         SC Freiburg   Maccabi Tel Aviv    1.35    6.54    9.44
1           Feyenoord         Sturm Graz    1.55    4.91    6.54
2               Brann     FC Midtjylland    3.68    3.58    2.23
3            Malmo FF   FK Crvena Zvezda    3.35    3.49    2.41
4             Bologna             Celtic    1.53    5.05    6.80
5      BSC Young Boys               Lyon    4.75    4.00    1.85
6               Plzen           FC Porto    4.26    3.79    2.00
7          Fenerbahçe        Aston Villa    4.34    3.82    1.97
8                PAOK         Real Betis    3.46    3.52    2.35
9                Nice    GO Ahead Eagles    1.64    4.54    5.84
10            Utrecht               Genk    2.77    3.43    2.88
11           SC Braga  Nottingham Forest    2.94    3.43    2.71
12            Rangers         Ludogorets    2.01    3.77    4.20
13            AS Roma      VfB Stuttgart    1.87    3.96    4.67
14         Celta Vigo              Lille    2.79    3.42    2.86
15  Red Bull Salzburg      FC Basel 1893    2.45    3.48    3.29
16      Dinamo Zagreb               FCSB    1.95    3.84    4.39
17    Ferencvarosi TC      Panathinaikos    2.33    3.52    3.48

In [13]:
# full table sim
# results = run_full_table_sims(**CONFIG, standings_df=standings_df)
# results.head(CONFIG['head_size'])

In [14]:
# top 8
winning_places = 8
results = run_multiple_sims(**CONFIG, standings_df=standings_df, number_of_winning_places=winning_places, reverse=False)
results.to_csv(f'data/sims/multiple_sims_league_{CONFIG["league_id"]}_top_{winning_places}_{datetime.today().strftime("%Y-%m-%d")}.csv', index=False)
results.head(CONFIG['head_size'])

100%|██████████| 10000/10000 [01:34<00:00, 105.79it/s]

10000 simulations
8 winning places

,Club,Elo,xPts,Wins,Wins in TB,Losses in TB,% Wins,% Wins + won TB,% Wins + all TB,Odds % Wins,Odds % Wins + won TB,Odds % Wins + all TB
1,Aston Villa,1912,19.49,9632,43,168,96.3,96.8,98.4,1.04,1.03,1.02
2,Lyon,1737,18.83,8867,566,133,88.7,94.3,95.7,1.13,1.06,1.05
3,FC Midtjylland,1679,18.72,8821,399,320,88.2,92.2,95.4,1.13,1.08,1.05
4,SC Freiburg,1711,17.38,7557,415,711,75.6,79.7,86.8,1.32,1.25,1.15
5,Real Betis,1756,17.53,7392,637,559,73.9,80.3,85.9,1.35,1.25,1.16
6,FC Porto,1768,17.18,6657,405,1401,66.6,70.6,84.6,1.5,1.42,1.18
7,SC Braga,1686,16.18,4427,726,1126,44.3,51.5,62.8,2.26,1.94,1.59
8,Ferencvarosi TC,1543,16.11,4220,130,1607,42.2,43.5,59.6,2.37,2.3,1.68
9,AS Roma,1808,15.84,3872,894,877,38.7,47.7,56.4,2.58,2.1,1.77
10,Bologna,1766,15.27,3134,1073,463,31.3,42.1,46.7,3.19,2.38,2.14
11,Nottingham Forest,1776,14.71,2180,768,350,21.8,29.5,33.0,4.59,3.39,3.03
12,VfB Stuttgart,1731,15.16,2033,1608,161,20.3,36.4,38.0,4.92,2.75,2.63
13,Fenerbahçe,1698,13.88,863,431,302,8.6,12.9,16.0,12,7.73,6.27
14,Genk,1591,13.38,353,177,766,3.5,5.3,13.0,28,19,7.72
15,FK Crvena Zvezda,1570,12.75,212,0,563,2.1,2.1,7.8,47,47,13
16,Panathinaikos,1543,11.92,193,148,70,1.9,3.4,4.1,52,29,24
17,Plzen,1566,12.27,152,433,48,1.5,5.9,6.3,66,17,16
18,PAOK,1616,10.98,1,137,0,0.0,1.4,1.4,10000,72,72
19,Celta Vigo,1683,11.87,4,228,10,0.0,2.3,2.4,2500,43,41
20,Lille,1754,12.06,5,207,61,0.0,2.1,2.7,2000,47,37
21,BSC Young Boys,1506,10.43,0,0,54,0.0,0.0,0.5,N/A,N/A,185
22,Brann,1523,10.45,0,0,1,0.0,0.0,0.0,N/A,N/A,10000
23,Ludogorets,1448,9.06,0,0,0,0.0,0.0,0.0,N/A,N/A,N/A
24,Celtic,1586,9.40,0,0,0,0.0,0.0,0.0,N/A,N/A,N/A
25,Dinamo Zagreb,1520,9.51,0,0,0,0.0,0.0,0.0,N/A,N/A,N/A
26,FC Basel 1893,1511,8.59,0,0,0,0.0,0.0,0.0,N/A,N/A,N/A
27,FCSB,1448,7.77,0,0,0,0.0,0.0,0.0,N/A,N/A,N/A
28,GO Ahead Eagles,1458,7.60,0,0,0,0.0,0.0,0.0,N/A,N/A,N/A
29,Sturm Graz,1462,6.01,0,0,0,0.0,0.0,0.0,N/A,N/A,N/A
30,Feyenoord,1638,5.92,0,0,0,0.0,0.0,0.0,N/A,N/A,N/A
31,Red Bull Salzburg,1495,4.75,0,0,0,0.0,0.0,0.0,N/A,N/A,N/A
32,Utrecht,1529,3.36,0,0,0,0.0,0.0,0.0,N/A,N/A,N/A
33,Rangers,1508,3.20,0,0,0,0.0,0.0,0.0,N/A,N/A,N/A
34,Malmo FF,1448,2.92,0,0,0,0.0,0.0,0.0,N/A,N/A,N/A
35,Maccabi Tel Aviv,1450,2.16,0,0,0,0.0,0.0,0.0,N/A,N/A,N/A
36,Nice,1606,3.71,0,0,0,0.0,0.0,0.0,N/A,N/A,N/A